name: Issue Tracker
on:
  issues:
    types: [opened, reopened, edited, closed, deleted]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "PXF Issue ${{ github.event.action }} by ${{ github.event.issue.user.login }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                   {
                                     "keyValue": {
                                          "content": "#${{ github.event.issue.number }} ${{ github.event.issue.title }}"
                                      }
                                   },
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "VIEW ISSUE",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.issue.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
